name: Youtube Live Catcher

on:
  schedule:
    - cron: '0 0/3 * * *'

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: config
        run: |
          git config --global user.email "lcdevilarte@hotmail.com"
          git config --global user.name "Luiz Carlos Devilarte"

      - name: Main
        run: |
          pwd
          chmod +x ytblive_catcher.sh
          ./ytblive_catcher.sh

      - name: git add
        run: |
          git add -A
          ls -la

      - name: commit & push
        run: |
          git commit -m "Canais Atualizados!"
          git push
